// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as CompTabs$RescriptReactIntro from "./CompTabs.bs.js";

import './site.css';
;

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component;
  var exit = 0;
  if (match) {
    switch (match.hd) {
      case "comp" :
          if (match.tl) {
            exit = 1;
          } else {
            component = React.createElement("div", undefined, "Tasks");
          }
          break;
      case "pilots" :
          if (match.tl) {
            exit = 1;
          } else {
            component = React.createElement("div", undefined, "Pilots");
          }
          break;
      case "settings" :
          if (match.tl) {
            exit = 1;
          } else {
            component = React.createElement("div", undefined, "Settings");
          }
          break;
      default:
        exit = 1;
    }
  } else {
    component = React.createElement("div", undefined, "Home page");
  }
  if (exit === 1) {
    component = React.createElement("div", undefined, "Route not found");
  }
  return React.createElement("div", undefined, React.createElement(CompTabs$RescriptReactIntro.make, {}), component);
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
