// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function mkTaskRows(tasks, taskLengths) {
  return Belt_List.zipBy(tasks, taskLengths, (function (param, d) {
                return {
                        taskName: param.taskName,
                        tps: Caml_splice_call.spliceObjApply("-", "concat", [Belt_List.toArray(Belt_List.map(param.zones.raw, (function (z) {
                                          return z.zoneName;
                                        })))]),
                        distance: d,
                        stopped: Belt_Option.isSome(param.stopped) ? true : false,
                        cancelled: Belt_Option.getWithDefault(param.cancelled, false)
                      };
              }));
}

function s(prim) {
  return prim;
}

function CompTasks(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("table", {
                  className: "table is-striped"
                }, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", undefined, "#"), React.createElement("th", {
                              className: "th-task-name"
                            }, "Name"), React.createElement("th", {
                              className: "th-task-tps"
                            }, "Turnpoints"), React.createElement("th", {
                              className: "th-task-dist"
                            }, "Distance"), React.createElement("th", {
                              className: "th-task-stopped"
                            }, "Stopped"), React.createElement("th", {
                              className: "th-task-cancelled"
                            }, "Cancelled"))), React.createElement("tbody", undefined, React.createElement("tr", undefined, React.createElement("td", undefined, "1"), React.createElement("td", {
                              className: "td-task-name"
                            }, "day one"), React.createElement("td", {
                              className: "td-task-tps"
                            }, "1DALBY-JANDOW-WARRA-1DALBY"), React.createElement("td", {
                              className: "td-task-dist"
                            }, "99.561444 km"), React.createElement("td", {
                              className: "td-task-stopped"
                            }), React.createElement("td", {
                              className: "td-task-cancelled"
                            })), React.createElement("tr", undefined, React.createElement("td", undefined, "1"), React.createElement("td", {
                              className: "td-task-name"
                            }, "day four T2"), React.createElement("td", {
                              className: "td-task-tps"
                            }, "1DALBY-MACALI-JIMBOU-WARRA-JANDOW-BRIGAL"), React.createElement("td", {
                              className: "td-task-dist"
                            }, "111.259762 km"), React.createElement("td", {
                              className: "td-task-stopped"
                            }), React.createElement("td", {
                              className: "td-task-cancelled"
                            })), React.createElement("tr", undefined, React.createElement("td", undefined, "1"), React.createElement("td", {
                              className: "td-task-name"
                            }, "day five"), React.createElement("td", {
                              className: "td-task-tps"
                            }, "1DALBY-BRIGAL-IRON-1DALBY"), React.createElement("td", {
                              className: "td-task-dist"
                            }, "96.889354 km"), React.createElement("td", {
                              className: "td-task-stopped"
                            }), React.createElement("td", {
                              className: "td-task-cancelled"
                            })), React.createElement("tr", undefined, React.createElement("td", undefined, "1"), React.createElement("td", {
                              className: "td-task-name"
                            }, "day six"), React.createElement("td", {
                              className: "td-task-tps"
                            }, "1DALBY-WARRA-BELL-1DALBY"), React.createElement("td", {
                              className: "td-task-dist"
                            }, "114.373717 km"), React.createElement("td", {
                              className: "td-task-stopped"
                            }), React.createElement("td", {
                              className: "td-task-cancelled"
                            })), React.createElement("tr", undefined, React.createElement("td", undefined, "1"), React.createElement("td", {
                              className: "td-task-name"
                            }, "day seven"), React.createElement("td", {
                              className: "td-task-tps"
                            }, "1DALBY-BROADW-JIMBOU-MACALI-1DALBY"), React.createElement("td", {
                              className: "td-task-dist"
                            }, "88.969527 km"), React.createElement("td", {
                              className: "td-task-stopped"
                            }), React.createElement("td", {
                              className: "td-task-cancelled"
                            })))));
}

var make = CompTasks;

export {
  mkTaskRows ,
  s ,
  make ,
  
}
/* react Not a pure module */
