// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function CompSettings(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("table", {
                  className: "table is-bordered"
                }, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", {
                              colSpan: 3
                            }), React.createElement("th", undefined, "Value"))), React.createElement("tbody", undefined, React.createElement("tr", undefined, React.createElement("th", undefined, "* Give"), React.createElement("td", {
                              colSpan: 2
                            }, "give fraction only, no give distance"), React.createElement("td", undefined, "0.005")), React.createElement("tr", undefined, React.createElement("th", undefined, "Earth model"), React.createElement("td", {
                              colSpan: 2
                            }, "Sphere with radius"), React.createElement("td", undefined, "6371000.0 m")), React.createElement("tr", undefined, React.createElement("th", {
                              colSpan: 3
                            }, "Earth math"), React.createElement("td", undefined, "Haversines"))), React.createElement("tfoot", undefined, React.createElement("tr", undefined, React.createElement("td", {
                              colSpan: 4
                            }, "* Adjusting the turnpoint radius with some give for pilots just short of the control zone")))));
}

var make = CompSettings;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
