// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function CompPilots(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("table", {
                  className: "table is-bordered is-striped"
                }, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", {
                              className: "th-pid"
                            }, "Id"), React.createElement("th", undefined, "Name"), React.createElement("th", undefined, "day one"), React.createElement("th", undefined, "day four T2"), React.createElement("th", undefined, "day five"), React.createElement("th", undefined, "day six"), React.createElement("th", undefined, "day seven"))), React.createElement("tbody", undefined, React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "35"), React.createElement("td", undefined, "Anatoly Reyter"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "16"), React.createElement("td", undefined, "Andrew Barnes"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "15"), React.createElement("td", undefined, "Andrew Sharpe"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "51"), React.createElement("td", undefined, "Billy Miller-Macleod"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "36"), React.createElement("td", undefined, "Brad Porter"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "24"), React.createElement("td", undefined, "Brodrick Osborne"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "10"), React.createElement("td", undefined, "Craig Taylor"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "49"), React.createElement("td", undefined, "Damian Peauril"), React.createElement("td", undefined, "DFNoTrack"), React.createElement("td", undefined, "DFNoTrack"), React.createElement("td", undefined, "DFNoTrack"), React.createElement("td", undefined, "DFNoTrack"), React.createElement("td", undefined, "DFNoTrack")), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "38"), React.createElement("td", undefined, "Dave Stevens"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "48"), React.createElement("td", undefined, "Derek Mckee"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "21"), React.createElement("td", undefined, "Frank Chetcuti"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "29"), React.createElement("td", undefined, "Guy Hubbard"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "27"), React.createElement("td", undefined, "Guy Williams"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "25"), React.createElement("td", undefined, "Hagen Bruggemann"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "46"), React.createElement("td", undefined, "Harrison Rowntree"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "40"), React.createElement("td", undefined, "Hossain Tefaili"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "7"), React.createElement("td", undefined, "James Atkinson"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "26"), React.createElement("td", undefined, "Jason Kath"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "28"), React.createElement("td", undefined, "John Harriot"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "37"), React.createElement("td", undefined, "John Spencer"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "5"), React.createElement("td", undefined, "Jonny Durand"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "44"), React.createElement("td", undefined, "Josh Woods"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "20"), React.createElement("td", undefined, "Konrad Heilmann"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "1"), React.createElement("td", undefined, "Mark Alton"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "13"), React.createElement("td", undefined, "Matthew Barlow"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "42"), React.createElement("td", undefined, "Mikhail Karmazin"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "4"), React.createElement("td", undefined, "Nick Purcell"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "33"), React.createElement("td", undefined, "Niki Longshore"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "23"), React.createElement("td", undefined, "Noel Collins"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "3"), React.createElement("td", undefined, "Paul Allen"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined, "NYP"), React.createElement("td", undefined, "ABS")), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "18"), React.createElement("td", undefined, "Peter Adriaans"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "41"), React.createElement("td", undefined, "Peter Burkitt"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "32"), React.createElement("td", undefined, "Rob Larkin"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "8"), React.createElement("td", undefined, "Rod Flockhart"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "9"), React.createElement("td", undefined, "Rohan Taylor"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "12"), React.createElement("td", undefined, "Rory Duncan"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "19"), React.createElement("td", undefined, "Scott Barrett"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "43"), React.createElement("td", undefined, "Simon West"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "22"), React.createElement("td", undefined, "Steve Blenkinsop"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "31"), React.createElement("td", undefined, "Tomas Kellner"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "2"), React.createElement("td", undefined, "Tony Armstrong"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "14"), React.createElement("td", undefined, "Tony Giammichele"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "17"), React.createElement("td", undefined, "Trevor Purcell"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "6"), React.createElement("td", undefined, "Viv Clements"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "34"), React.createElement("td", undefined, "dave moore"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "39"), React.createElement("td", undefined, "rob degroot"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)), React.createElement("tr", undefined, React.createElement("td", {
                              className: "td-pid"
                            }, "45"), React.createElement("td", undefined, "steve crosby"), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined), React.createElement("td", undefined)))));
}

var make = CompPilots;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
