// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import ReportWebVitals from "./reportWebVitals";
import * as App$RescriptReactIntro from "./App.bs.js";

import './site.css';
;

function reportWebVitals(prim) {
  ReportWebVitals();
  
}

var root = document.querySelector("#rescript");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$RescriptReactIntro.make, {}), root);
}

ReportWebVitals();

var root$1 = (root == null) ? undefined : Caml_option.some(root);

export {
  reportWebVitals ,
  root$1 as root,
  
}
/*  Not a pure module */
