// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function getComp(haveUrl, url, set) {
  if (!haveUrl) {
    return ;
  }
  var dataUrl = url + "/comp-input/comps.json";
  var __x = fetch(dataUrl);
  var __x$1 = __x.then(function (prim) {
        return prim.json();
      });
  __x$1.then(function (x) {
        return Promise.resolve(Curry._1(set, (function (param) {
                          return x;
                        })));
      });
  
}

var nullComp = {
  compName: "",
  scoreBack: undefined,
  utcOffset: {
    timeZoneMinutes: 0
  },
  from: "",
  to: "",
  location: "",
  earth: {
    sphere: {
      radius: ""
    }
  },
  earthMath: "",
  give: {
    giveDistance: undefined,
    giveFraction: 0.0
  }
};

export {
  nullComp ,
  getComp ,
  
}
/* No side effect */
